/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  businessName?: string;
  address?: string;
  phone?: string;
  instagramLink?: string;
  menus?: Array<{
    title?: string;
    slug?: string;
    _type: "menuItem";
    _key: string;
  }>;
  copyrights?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  intro?: string;
};

export type PageMeta = {
  _type: "pageMeta";
  title?: string;
  description?: string;
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "singleImage";
    _key: string;
  }>;
};

export type Locations = {
  _id: string;
  _type: "locations";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  allLocations?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    title?: string;
    address?: string;
    phone?: string;
    mapUrl?: string;
    orderLink?: string;
    _type: "location";
    _key: string;
  }>;
};

export type CateringMenu = {
  _id: string;
  _type: "cateringMenu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  options?: Array<{
    title?: string;
    additionalInfo?: string;
    details?: BlockContent;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    _type: "option";
    _key: string;
  }>;
  note?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageMetadata?: PageMeta;
  menuType?: "small-plates" | "sides" | "tacos" | "burritos-and-bowls" | "quesadillas" | "shareables-and-ultimate-nachos" | "beyond-taco" | "tcb-ramen" | "kids-menu" | "desserts" | "drinks" | "cocktails";
  smallPlates?: Array<{
    hasSubItems?: boolean;
    itemWithNoSubItems?: {
      hasLogo?: boolean;
      title?: string;
      price?: string;
      description?: string;
    };
    itemWithSubItems?: {
      title?: string;
      description?: string;
      items?: Array<{
        title?: string;
        price?: string;
        _type: "item";
        _key: string;
      }>;
    };
    _type: "menuItem";
    _key: string;
  }>;
  smallPlatesImageContent?: {
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
  };
  sides?: Array<{
    title?: string;
    price?: string;
    description?: string;
    isTopPick?: boolean;
    isTopPickItem?: {
      title?: string;
      description?: string;
      logo?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        altText?: string;
        _type: "image";
      };
    };
    _type: "item";
    _key: string;
  }>;
  tacos?: Array<{
    title?: string;
    description?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "tacoMenus";
    _key: string;
  }>;
  burritos?: Array<{
    title?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "burritosMenus";
    _key: string;
  }>;
  upgrade?: {
    title?: string;
    content?: BlockContent;
  };
  extras?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      _type: "item";
      _key: string;
    }>;
  };
  quesadillas?: Array<{
    title?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "quesadillasMenus";
    _key: string;
  }>;
  extrasQuesadillas?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      _type: "item";
      _key: string;
    }>;
  };
  shareables?: {
    title?: string;
    subTitle?: BlockContent;
    items?: Array<{
      title?: string;
      items?: Array<{
        title?: string;
        price?: string;
        additionalText?: string;
        description?: string;
        isVegeterian?: boolean;
        isSpicy?: boolean;
        spicyCount?: number;
        hasLogo?: boolean;
        block?: BlockContent;
        _type: "item";
        _key: string;
      }>;
      _type: "item";
      _key: string;
    }>;
  };
  beyondTaco?: {
    title?: string;
    description?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  tcbRamen?: {
    title?: string;
    description?: BlockContent;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  kidsMenu?: {
    title?: string;
    description?: string;
    items?: Array<{
      title?: string;
      name?: string;
      additionalText?: string;
      text2?: string;
      text2Details?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  desserts?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  drinks?: {
    title?: string;
    drinksMain?: Array<{
      title?: string;
      block?: BlockContent;
      _type: "drink";
      _key: string;
    }>;
  };
  drinksCombos?: Array<{
    title?: string;
    name?: string;
    hasLogo?: boolean;
    content?: BlockContent;
    _type: "item";
    _key: string;
  }>;
  cocktails?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  lottieFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  menu?: Array<{
    title?: string;
    slug?: string;
    hasSubMenu?: boolean;
    subMenus?: Array<{
      title?: string;
      slug?: string;
      _type: "subMenu";
      _key: string;
    }>;
    _type: "menuItem";
    _key: string;
  }>;
  cta?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  body?: BlockContent;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Footer | SanityImageCrop | SanityImageHotspot | About | PageMeta | Gallery | Locations | CateringMenu | BlockContent | Menu | Slug | Home | Header | Post | Author | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: HEADERQUERY
// Query: *[_type == 'header'][0]
export type HEADERQUERYResult = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  menu?: Array<{
    title?: string;
    slug?: string;
    hasSubMenu?: boolean;
    subMenus?: Array<{
      title?: string;
      slug?: string;
      _type: "subMenu";
      _key: string;
    }>;
    _type: "menuItem";
    _key: string;
  }>;
  cta?: string;
} | null;
// Variable: HOMEQUERY
// Query: *[_type == 'home'][0] {    _updatedAt,title,pageMetadata,    lottieFile {    asset-> {    url}        }        }
export type HOMEQUERYResult = {
  _updatedAt: string;
  title: string | null;
  pageMetadata: PageMeta | null;
  lottieFile: {
    asset: {
      url: string | null;
    } | null;
  } | null;
} | null;
// Variable: POSTSQUERY
// Query: *[_type == 'post']
export type POSTSQUERYResult = Array<{
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  body?: BlockContent;
}>;
// Variable: ALLMENUS
// Query: *[_type == 'menu' && defined(slug.current)]
export type ALLMENUSResult = Array<{
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: Slug;
  pageMetadata?: PageMeta;
  menuType?: "beyond-taco" | "burritos-and-bowls" | "cocktails" | "desserts" | "drinks" | "kids-menu" | "quesadillas" | "shareables-and-ultimate-nachos" | "sides" | "small-plates" | "tacos" | "tcb-ramen";
  smallPlates?: Array<{
    hasSubItems?: boolean;
    itemWithNoSubItems?: {
      hasLogo?: boolean;
      title?: string;
      price?: string;
      description?: string;
    };
    itemWithSubItems?: {
      title?: string;
      description?: string;
      items?: Array<{
        title?: string;
        price?: string;
        _type: "item";
        _key: string;
      }>;
    };
    _type: "menuItem";
    _key: string;
  }>;
  smallPlatesImageContent?: {
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
  };
  sides?: Array<{
    title?: string;
    price?: string;
    description?: string;
    isTopPick?: boolean;
    isTopPickItem?: {
      title?: string;
      description?: string;
      logo?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        altText?: string;
        _type: "image";
      };
    };
    _type: "item";
    _key: string;
  }>;
  tacos?: Array<{
    title?: string;
    description?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "tacoMenus";
    _key: string;
  }>;
  burritos?: Array<{
    title?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "burritosMenus";
    _key: string;
  }>;
  upgrade?: {
    title?: string;
    content?: BlockContent;
  };
  extras?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      _type: "item";
      _key: string;
    }>;
  };
  quesadillas?: Array<{
    title?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "quesadillasMenus";
    _key: string;
  }>;
  extrasQuesadillas?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      _type: "item";
      _key: string;
    }>;
  };
  shareables?: {
    title?: string;
    subTitle?: BlockContent;
    items?: Array<{
      title?: string;
      items?: Array<{
        title?: string;
        price?: string;
        additionalText?: string;
        description?: string;
        isVegeterian?: boolean;
        isSpicy?: boolean;
        spicyCount?: number;
        hasLogo?: boolean;
        block?: BlockContent;
        _type: "item";
        _key: string;
      }>;
      _type: "item";
      _key: string;
    }>;
  };
  beyondTaco?: {
    title?: string;
    description?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  tcbRamen?: {
    title?: string;
    description?: BlockContent;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  kidsMenu?: {
    title?: string;
    description?: string;
    items?: Array<{
      title?: string;
      name?: string;
      additionalText?: string;
      text2?: string;
      text2Details?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  desserts?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  drinks?: {
    title?: string;
    drinksMain?: Array<{
      title?: string;
      block?: BlockContent;
      _type: "drink";
      _key: string;
    }>;
  };
  drinksCombos?: Array<{
    title?: string;
    name?: string;
    hasLogo?: boolean;
    content?: BlockContent;
    _type: "item";
    _key: string;
  }>;
  cocktails?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
}>;
// Variable: SINGLEMENU
// Query: *[_type == 'menu' && slug.current == $slug][0]
export type SINGLEMENUResult = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageMetadata?: PageMeta;
  menuType?: "beyond-taco" | "burritos-and-bowls" | "cocktails" | "desserts" | "drinks" | "kids-menu" | "quesadillas" | "shareables-and-ultimate-nachos" | "sides" | "small-plates" | "tacos" | "tcb-ramen";
  smallPlates?: Array<{
    hasSubItems?: boolean;
    itemWithNoSubItems?: {
      hasLogo?: boolean;
      title?: string;
      price?: string;
      description?: string;
    };
    itemWithSubItems?: {
      title?: string;
      description?: string;
      items?: Array<{
        title?: string;
        price?: string;
        _type: "item";
        _key: string;
      }>;
    };
    _type: "menuItem";
    _key: string;
  }>;
  smallPlatesImageContent?: {
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
  };
  sides?: Array<{
    title?: string;
    price?: string;
    description?: string;
    isTopPick?: boolean;
    isTopPickItem?: {
      title?: string;
      description?: string;
      logo?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        altText?: string;
        _type: "image";
      };
    };
    _type: "item";
    _key: string;
  }>;
  tacos?: Array<{
    title?: string;
    description?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "tacoMenus";
    _key: string;
  }>;
  burritos?: Array<{
    title?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "burritosMenus";
    _key: string;
  }>;
  upgrade?: {
    title?: string;
    content?: BlockContent;
  };
  extras?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      _type: "item";
      _key: string;
    }>;
  };
  quesadillas?: Array<{
    title?: string;
    tacosItems?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      _type: "single";
      _key: string;
    }>;
    _type: "quesadillasMenus";
    _key: string;
  }>;
  extrasQuesadillas?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      _type: "item";
      _key: string;
    }>;
  };
  shareables?: {
    title?: string;
    subTitle?: BlockContent;
    items?: Array<{
      title?: string;
      items?: Array<{
        title?: string;
        price?: string;
        additionalText?: string;
        description?: string;
        isVegeterian?: boolean;
        isSpicy?: boolean;
        spicyCount?: number;
        hasLogo?: boolean;
        block?: BlockContent;
        _type: "item";
        _key: string;
      }>;
      _type: "item";
      _key: string;
    }>;
  };
  beyondTaco?: {
    title?: string;
    description?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  tcbRamen?: {
    title?: string;
    description?: BlockContent;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  kidsMenu?: {
    title?: string;
    description?: string;
    items?: Array<{
      title?: string;
      name?: string;
      additionalText?: string;
      text2?: string;
      text2Details?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  desserts?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
  drinks?: {
    title?: string;
    drinksMain?: Array<{
      title?: string;
      block?: BlockContent;
      _type: "drink";
      _key: string;
    }>;
  };
  drinksCombos?: Array<{
    title?: string;
    name?: string;
    hasLogo?: boolean;
    content?: BlockContent;
    _type: "item";
    _key: string;
  }>;
  cocktails?: {
    title?: string;
    items?: Array<{
      title?: string;
      price?: string;
      additionalText?: string;
      description?: string;
      isVegeterian?: boolean;
      isSpicy?: boolean;
      spicyCount?: number;
      hasLogo?: boolean;
      block?: BlockContent;
      _type: "item";
      _key: string;
    }>;
  };
} | null;
// Variable: CATERINGMENU
// Query: *[_type == 'cateringMenu'][0]
export type CATERINGMENUResult = {
  _id: string;
  _type: "cateringMenu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  options?: Array<{
    title?: string;
    additionalInfo?: string;
    details?: BlockContent;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    _type: "option";
    _key: string;
  }>;
  note?: string;
} | null;
// Variable: LOCATIONSQUERY
// Query: *[_type == 'locations'][0]
export type LOCATIONSQUERYResult = {
  _id: string;
  _type: "locations";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  allLocations?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    title?: string;
    address?: string;
    phone?: string;
    mapUrl?: string;
    orderLink?: string;
    _type: "location";
    _key: string;
  }>;
} | null;
// Variable: GALLERYQUERY
// Query: *[_type == 'gallery'][0]
export type GALLERYQUERYResult = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "singleImage";
    _key: string;
  }>;
} | null;
// Variable: ABOUTQUERY
// Query: *[_type == 'about'][0]
export type ABOUTQUERYResult = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageMetadata?: PageMeta;
  intro?: string;
} | null;
// Variable: FOOTERQUERY
// Query: *[_type == 'footer'][0]
export type FOOTERQUERYResult = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  businessName?: string;
  address?: string;
  phone?: string;
  instagramLink?: string;
  menus?: Array<{
    title?: string;
    slug?: string;
    _type: "menuItem";
    _key: string;
  }>;
  copyrights?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == 'header'][0]\n    ": HEADERQUERYResult;
    "\n    *[_type == 'home'][0] {\n    _updatedAt,\ntitle,\npageMetadata,\n    lottieFile {\n    asset-> {\n    url}\n    \n    }\n    \n    }\n    ": HOMEQUERYResult;
    "\n    *[_type == 'post']\n    ": POSTSQUERYResult;
    "\n    *[_type == 'menu' && defined(slug.current)]\n    ": ALLMENUSResult;
    "\n    *[_type == 'menu' && slug.current == $slug][0]\n    ": SINGLEMENUResult;
    "\n    *[_type == 'cateringMenu'][0]\n    ": CATERINGMENUResult;
    "\n    *[_type == 'locations'][0]\n    ": LOCATIONSQUERYResult;
    "\n    *[_type == 'gallery'][0]\n    ": GALLERYQUERYResult;
    "\n    *[_type == 'about'][0]\n    ": ABOUTQUERYResult;
    "\n    *[_type == 'footer'][0]\n    ": FOOTERQUERYResult;
  }
}
